### ISSUE TITLE
Error: near line 1: near "0": syntax error

### ISSUE THREAD

**Issue by Alexvroum** [empierre/domoticz_gaspar#10]
<code>
abe@hmcenter:~/Dom/plugins/domoticz_gaspar$ cat req.sql | /usr/bin/sqlite3 /home/abe/Dom/domoticz.db
abe@hmcenter:~/Dom/plugins/domoticz_gaspar$ ./domoticz_gaspar.sh
Error: near line 1: near "0": syntax error
abe@hmcenter:~/Dom/plugins/domoticz_gaspar$ cat req.sql
0
338
143
Exception opening export_months_values.json : TypeError: Cannot read property 'conso' of undefined
DELETE FROM 'Meter_Calendar' WHERE devicerowid=3 and date = '2019-09-30'; INSERT INTO 'Meter_Calendar' (DeviceRowID,Value,Counter,Date) VALUES (3, '8000', '481', '2019-09-30');
DELETE FROM 'Meter_Calendar' WHERE devicerowid=3 and date = '2019-10-01'; INSERT INTO 'Meter_Calendar' (DeviceRowID,Value,Counter,Date) VALUES (3, '6000', '489', '2019-10-01');
DELETE FROM 'Meter_Calendar' WHERE devicerowid=3 and date = '2019-10-02'; INSERT INTO 'Meter_Calendar' (DeviceRowID,Value,Counter,Date) VALUES (3, '6000', '495', '2019-10-02');
DELETE FROM 'Meter_Calendar' WHERE devicerowid=3 and date = '2019-10-03'; INSERT INTO 'Meter_Calendar' (DeviceRowID,Value,Counter,Date) VALUES (3, '43000', '501', '2019-10-03');
DELETE FROM 'Meter_Calendar' WHERE devicerowid=3 and date = '2019-10-04'; INSERT INTO 'Meter_Calendar' (DeviceRowID,Value,Counter,Date) VALUES (3, '23000', '544', '2019-10-04');
DELETE FROM 'Meter_Calendar' WHERE devicerowid=3 and date = '2019-10-05'; INSERT INTO 'Meter_Calendar' (DeviceRowID,Value,Counter,Date) VALUES (3, '14000', '567', '2019-10-05');
DELETE FROM 'Meter_Calendar' WHERE devicerowid=3 and date = '2019-10-06'; INSERT INTO 'Meter_Calendar' (DeviceRowID,Value,Counter,Date) VALUES (3, '7000', '581', '2019-10-06');
DELETE FROM 'Meter_Calendar' WHERE devicerowid=3 and date = '2019-10-07'; INSERT INTO 'Meter_Calendar' (DeviceRowID,Value,Counter,Date) VALUES (3, '22000', '588', '2019-10-07');
DELETE FROM 'Meter_Calendar' WHERE devicerowid=3 and date = '2019-10-08'; INSERT INTO 'Meter_Calendar' (DeviceRowID,Value,Counter,Date) VALUES (3, '1000', '610', '2019-10-08');
DELETE FROM 'Meter_Calendar' WHERE devicerowid=3 and date = '2019-10-09'; INSERT INTO 'Meter_Calendar' (DeviceRowID,Value,Counter,Date) VALUES (3, '4000', '611', '2019-10-09');
DELETE FROM 'Meter_Calendar' WHERE devicerowid=3 and date = '2019-10-10'; INSERT INTO 'Meter_Calendar' (DeviceRowID,Value,Counter,Date) VALUES (3, '7000', '615', '2019-10-10');
DELETE FROM 'Meter_Calendar' WHERE devicerowid=3 and date = '2019-10-11'; INSERT INTO 'Meter_Calendar' (DeviceRowID,Value,Counter,Date) VALUES (3, '10000', '622', '2019-10-11');
abe@hmcenter:~/Dom/plugins/domoticz_gaspar$ cat req.sql | /usr/bin/sqlite3 /home/abe/Dom/domoticz.db
Error: near line 1: near "0": syntax error
</code>

**Comment by Alexvroum** [comment]
Bonjour,

Je viens de mettre en place le plugin les insert se font correctement mais les premières lignes ne passes pas.

J'aurais aimé aider mais je ne suis pas doué en js...

Après j'ai peut être pas assez de data à remonter....
Merci.

Cdlt,

**Comment by empierre** [comment]
Hello tu es sur le dernier code de git ?

**Comment by Alexvroum** [comment]
oui, je l'ai dl ce matin.

Je l'ai reclone et j'ai ma première erreur avec winston => je passe à winston2

**Comment by empierre** [comment]
Hello,
il y a du rebut au debut du fichier de logs, sinon tout le reste est bon, aucun soucis, je pousse un correctif
