### ISSUE TITLE
Feature Request : MQTT

### ISSUE THREAD

**Issue by Minims** [empierre/domoticz_gaspar#11]
Hello,

Est ce que l'envoi des données de consommation jasper  dans un topic MQTT est envisageable ? Merci

**Comment by empierre** [comment]
Hello,

  si tu sais me dire comment faire oui ;-)

  pour l'instant j'ai fait très simple en générant du sql, mais si tu as un format d'envoi et quelques liens voir un script d'exemple je peux essayer de l'intégrer

**Comment by empierre** [comment]
sudo npm install -g mqtt url request
sudo apt-get install mosquitto-clients

mosquitto_pub -h localhost -m '{ "idx" : 559, "nvalue" : 0, "svalue" : "Value;Counter" }' -t 'domoticz/in'

**Comment by empierre** [comment]
La limitation que je vois est qu'en insérant en base je maitrise ce que je supprime ou ajoute, là je ne sais pas quel sera le comportement de celui qui reçoit. Par exemple je ne vois pas où passer la date...

tu vas recevoir la donnée sur quel type de device ?

**Comment by Minims** [comment]
Je veux mettre la donnée dans Mosquitto sur un raspberry et ensuite pouvoir la récupérer avec un soft comme home assistant, domoticz ou en encore Jeedom. Comme ca ton plugin devient generic et tout le monde peut ensuite gérer la donnée comme il le souhaite sans forcement être sous domoticz.

Voici une idée de message, le message peut être un json.

-t GasPar/Consommation/Day -m "{"CONSO":123.4,"DATE":"2019-10-14"}"
-t GasPar/Consommation/Month -m "{"CONSO":123.4,"YEAR":2019,"MONTH":10}"
-t GasPar/Consommation/Year -m "{"CONSO":123.4,"YEAR":2019}"

**Comment by Minims** [comment]
Si tu fais du python voici un exemple qui push des données du RFLINK dans un topic Mqtt : https://github.com/Iture/RFLinkGateway

**Comment by Minims** [comment]
Est q'un paquet "pip" pygaspar avec juste les fonctions de recuperation des données serait envisageable ? 
Comme ceci tout le monde peut l'intégrer comme il le souhaite dans la platforme de son choix. Merci.

Comme plinky par exemple :-) : https://github.com/Pirionfr/pyLinky

**Comment by goldendatahub** [comment]
Bonjour, j'ai créé un projet [gazpar2mqtt](https://github.com/yukulehe/gazpar2mqtt) grandement inspiré de domoticz_gazpar. 
Le script python publie les derniers relevés vers un broker mqtt.

**Comment by Sebastiii** [comment]
@yukulehe ton projet fonctionne bien, merci ;)
Le projet 'domoticz_gaspar', je n'ai pas réussi à le faire fonctionner, en tout cas, super pour tout le travail que @empierre a fait, car ça a permis de faire avancer les choses 👍

Bon finalement en passant par un docker Linux sous Synology, j'arrive à faire fonctionner le plugin  "domoticz_gaspar" ;)
Effectivement, je n'avais pas fait gaffe aux dates, du coup, on n’a pas le temps réel, j'avais transformé la chaine du plugin "yukulehe" mais les données reçues ne sont pas correcte vu qu'il y a un décalage de date :)

Par contre, on peut bien avoir la valeur en m3.

**Comment by empierre** [comment]
il faut maintenant passer sur l'autre plugin, cf page d'accueil
