### ISSUE TITLE
Bonjour Emmanuel

### ISSUE THREAD

**Issue by dranreb38** [empierre/domoticz_gaspar#13]
Bonjour Emmanuel

Je suis sur un Raspberry 3 B+, oui sous buster
 
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

_Originally posted by @disquette38 in https://github.com/empierre/domoticz_gaspar/issues/12#issuecomment-565789959_

**Comment by empierre** [comment]
dupl of #14

**Comment by empierre** [comment]
as-tu bien installé:
npm install winston@2.4.2

sinon essayes en 2.2.0:
npm install winston@2.2.0

**Comment by dranreb38** [comment]
Bon visiblement en winston@2.2.0  (cela ne fonctionne pas en winston@2.4.2) 
C'est un peu mieux, plus de msg d'erreur dans le log mais ceci en lancement du script:
`Error: near line 1: near "Exception": syntax error
Error: near line 3: attempt to write a readonly database
Error: near line 4: attempt to write a readonly database
Error: near line 5: attempt to write a readonly database
Error: near line 6: attempt to write a readonly database
Error: near line 7: attempt to write a readonly database
`
Et pour la première fois j'ai bien le fichier req.sql mais avec un msg 
"Exception opening export_months_values.json : TypeError: Cannot read property 'conso' of undefined"

cat export_months_values.json > [{"conso": "388", "time": "12/2019"}]

Et rien dans domoticz

**Comment by dranreb38** [comment]
Apres avoir relancer le script, dans le fichier de log
`2019-12-15 15:31:48,129 logging in as xxxxx@xxxx.fr
2019-12-15 15:31:55,203 logged in successfully!
2019-12-15 15:31:55,204 retrieving data...
Traceback (most recent call last):
  File "/home/pi/domoticz/domoticz_gaspar/gaspar_json.py", line 179, in <module>
    main()
  File "/home/pi/domoticz/domoticz_gaspar/gaspar_json.py", line 124, in main
    dtostr(today))
  File "/home/pi/domoticz/domoticz_gaspar/gaspar.py", line 150, in get_data_per_month
    return _get_data(session, 'Mois', start_date, end_date)
  File "/home/pi/domoticz/domoticz_gaspar/gaspar.py", line 300, in _get_data
    d = md.group(1)
AttributeError: 'NoneType' object has no attribute 'group'

`

**Comment by empierre** [comment]
hello, tu as toujour le bug ? on vient de corriger quelque chose de similaire
