### ISSUE TITLE
Bonjour Emmanuel,

### ISSUE THREAD

**Issue by dranreb38** [empierre/domoticz_gaspar#14]
Bonjour Emmanuel

Oui sous Buster, Raspberry 3 B+

Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

_Originally posted by @disquette38 in https://github.com/empierre/domoticz_gaspar/issues/12#issuecomment-565789959_

**Comment by empierre** [comment]
je suis sous buster, pas de soucis pour moi
