### ISSUE TITLE
Recuperer les données de Gaspar dans un Event domoticz

### ISSUE THREAD

**Issue by usky73** [empierre/domoticz_gaspar#15]
Bonjour Pierre et un grand merci pour ce dev. Ca marche très bien sauf... que je ne peux rien faire des valeurs récupérées !
Le compteur affiche toujours 0 et la date d'update ne change pas (meme si les valeurs de la veille se mettent bien à jour). Et je vois bien pourquoi.
Mon soucis c'est que du coup je n'arrive pas à récupérer ces valeurs dans un script Domoticz vu que dzvents ne propose que la valeur actuelle.
Je voulais parametrer une alarme sur le aconso et  stocker ces infos dans une base mysql séparée de domoticz pour garder l'historique journalier. Il me semblait que domoticz faisait du nettoyage.

**Comment by empierre** [comment]
Hello,

  C'est normal ce n'est pas du temps réel, et de plus il y a des
limitations domoticz...

**Comment by usky73** [comment]
Comme je l'ai écrit plus haut, je comprend pourquoi domoticz n'affiche pas de valeur.
Par contre je cherche un moyen de récuperer cette info ! Dans domoticz ou ailleurs.
Une idée ?

**Comment by empierre** [comment]
non pas pour l'instant...

**Comment by empierre** [comment]
il faut maintenant passer sur l'autre plugin, cf page d'accueil
