### ISSUE TITLE
Pas d'enregistrement si la conso est nulle

### ISSUE THREAD

**Issue by usky73** [empierre/domoticz_gaspar#16]
Bonjour,
J'utilise ce plugin depuis 4 mois maintenant sans gros soucis.
Par ces derniers temps le soleil et les températures clémentes sont de retour. Mes panneaux solaires thermiques produisent toute l'eau chaude. 
Je viens donc d'avoir mes premieres consommations nulles.
Ce qui me gène c'est que je ne peux pas faire la différence entre une conso nulle et une valeur manquante - ce qui arrive régulièrement quand la valeur n'existe pas sur le site de grdf.
Serait il possible de rajouter les valeurs nulle dans domoticz ?

**Comment by empierre** [comment]
Hello, peux-tu m'envoyer ton req.sql que je vois ce que te donne le site grdf ?domoticz@e-nef.com

**Comment by usky73** [comment]
Bonjour,



J'ai attaché le fichier demandé.



Merci de ton aide.



Laurent - usky73


---- Le sam., 21 mars 2020 21:21:53 +0100 Emmanuel <notifications@github.com> écrit ----




Hello, peux-tu m'envoyer ton req.sql que je vois ce que te donne le site grdf ?mailto:domoticz@e-nef.com

**Comment by usky73** [comment]
Quelques precisions sur les relevés. La conso du 19 est nulle, elle n'apparait donc pas dans les lignes req.sql.

Ce n'est pas un bug en soit mais j'avais trouvé cette astuce pour faire la différence entre une valeur nulle et une valeur manquante.



A+



Laurent 



---- Le dim., 22 mars 2020 11:34:22 +0100 LAURENT TERCINET <lterci@zohomail.eu> écrit ----


Bonjour,



J'ai attaché le fichier demandé.



Merci de ton aide.



Laurent - usky73



---- Le sam., 21 mars 2020 21:21:53 +0100 Emmanuel <mailto:notifications@github.com> écrit ----












Hello, peux-tu m'envoyer ton req.sql que je vois ce que te donne le site grdf ?mailto:domoticz@e-nef.com

**Comment by empierre** [comment]
Hello,

  Je n'ai rien vu d'attaché (pas sur que github le gère)

  donc export_days_values.json  et req.sql que je vois si j'ai quelque chose dans l'un pour faire ça dans l'autre

**Comment by usky73** [comment]
Arg, je ne suis pas habitué à github, j'ai répondu par mail...

Ci dessous les fichiers demandés :
**req.sql**
`DELETE FROM 'Meter_Calendar' WHERE devicerowid=611 and date = '2020-03-10'; INSERT INTO 'Meter_Calendar' (DeviceRowID,Value,Counter,Date) VALUES (611, '133000', '2320', '2020-03-10');
DELETE FROM 'Meter_Calendar' WHERE devicerowid=611 and date = '2020-03-11'; INSERT INTO 'Meter_Calendar' (DeviceRowID,Value,Counter,Date) VALUES (611, '32000', '2453', '2020-03-11');
DELETE FROM 'Meter_Calendar' WHERE devicerowid=611 and date = '2020-03-12'; INSERT INTO 'Meter_Calendar' (DeviceRowID,Value,Counter,Date) VALUES (611, '28000', '2485', '2020-03-12');
DELETE FROM 'Meter_Calendar' WHERE devicerowid=611 and date = '2020-03-13'; INSERT INTO 'Meter_Calendar' (DeviceRowID,Value,Counter,Date) VALUES (611, '68000', '2513', '2020-03-13');
DELETE FROM 'Meter_Calendar' WHERE devicerowid=611 and date = '2020-03-14'; INSERT INTO 'Meter_Calendar' (DeviceRowID,Value,Counter,Date) VALUES (611, '79000', '2581', '2020-03-14');
DELETE FROM 'Meter_Calendar' WHERE devicerowid=611 and date = '2020-03-15'; INSERT INTO 'Meter_Calendar' (DeviceRowID,Value,Counter,Date) VALUES (611, '17000', '2660', '2020-03-15');
DELETE FROM 'Meter_Calendar' WHERE devicerowid=611 and date = '2020-03-16'; INSERT INTO 'Meter_Calendar' (DeviceRowID,Value,Counter,Date) VALUES (611, '1000', '2677', '2020-03-16');
DELETE FROM 'Meter_Calendar' WHERE devicerowid=611 and date = '2020-03-17'; INSERT INTO 'Meter_Calendar' (DeviceRowID,Value,Counter,Date) VALUES (611, '2000', '2678', '2020-03-17');
DELETE FROM 'Meter_Calendar' WHERE devicerowid=611 and date = '2020-03-18'; INSERT INTO 'Meter_Calendar' (DeviceRowID,Value,Counter,Date) VALUES (611, '1000', '2680', '2020-03-18');
DELETE FROM 'Meter_Calendar' WHERE devicerowid=611 and date = '2020-03-20'; INSERT INTO 'Meter_Calendar' (DeviceRowID,Value,Counter,Date) VALUES (611, '3000', '2681', '2020-03-20');
DELETE FROM 'Meter_Calendar' WHERE devicerowid=611 and date = '2020-03-21'; INSERT INTO 'Meter_Calendar' (DeviceRowID,Value,Counter,Date) VALUES (611, '2000', '2684', '2020-03-21');
`

Tu peux noter que le date du 19 (avec conso nulle) n'est pas dans le fichier sql

**export_days_values.json**
`[{"conso": "133", "time": "10/03/2020"}, {"conso": "32", "time": "11/03/2020"}, {"conso": "28", "time": "12/03/2020"}, {"conso": "68", "time": "13/03/2020"}, {"conso": "79", "time": "14/03/2020"}, {"conso": "17", "time": "15/03/2020"}, {"conso": "1", "time": "16/03/2020"}, {"conso": "2", "time": "17/03/2020"}, {"conso": "1", "time": "18/03/2020"}, {"conso": "0", "time": "19/03/2020"}, {"conso": "3", "time": "20/03/2020"}, {"conso": "2", "time": "21/03/2020"}]`

**Comment by empierre** [comment]
Hello,

  commité !

**Comment by usky73** [comment]
Hello
Pas de nouvelles mesures depuis 2 jours alors qu'elles sont sur le site (31/03 et 01/04)
Ci joint le log

> 2020-04-02 17:05:02,813 logging in as xxxxx@mail.com...
2020-04-02 17:05:12,286 logged in successfully!
2020-04-02 17:05:12,287 retrieving data...
Traceback (most recent call last):
  File "/home/pi/domoticz/domoticz_gaspar/gaspar_json.py", line 179, in <module>
    main()
  File "/home/pi/domoticz/domoticz_gaspar/gaspar_json.py", line 124, in main
    dtostr(today))
  File "/home/pi/domoticz/domoticz_gaspar/gaspar.py", line 150, in get_data_per_month
    return _get_data(session, 'Mois', start_date, end_date)
  File "/home/pi/domoticz/domoticz_gaspar/gaspar.py", line 300, in _get_data
    d = md.group(1)
AttributeError: 'NoneType' object has no attribute 

> 'group'
Si tu as une idée, ell est bien venue

**Comment by empierre** [comment]
Site un stable il faut relancer plusieurs fois...

**Comment by usky73** [comment]
Bonjour et merci du retour.
J'avais déjà eu ce soucis mais les valeurs n'étaient pas sur le site de grdf, du coup le probleme était vraiment chez eux. C'était la 1ere fois que les valeurs étaient bien chez grdf mais pas chargées... Du coup inquiétude!
Mais tout est rentré dans l'ordre.

Petite question suite au commit. Je ne suis pas habitué à ce processus. Commit = fait ?
Comment mettre à jour ?

Encore merci pour le commit !

**Comment by empierre** [comment]
Hello,

  Si tu avais récupéré du git, tu vas dans ton répertoire s'installe et tu
fais
 git pull

**Comment by usky73** [comment]
Juste un petit retour, ca marche nickel. Je l'utilise maintenant depuis début Janvier (activation des données par GDF) et je n'ai aucun soucis y compris avec la derniere mise à jour (raspbian & domoticz) faite la semaine dernière (buster & domoticz Version: 4.10717)
Voilà, encore merci.

**Comment by empierre** [comment]
Merci !
