### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by TheSleepySlee** [empierre/domoticz_gaspar#19]
Hello,

Avant d'être confronté au probleme de certificat, j'avais fréquemment cette erreur:

```
2020-08-14 18:00:09,488 logged in successfully!
2020-08-14 18:00:09,488 retrieving data...
Traceback (most recent call last):
  File "/etc/openhab2/scripts/gazpar/domoticz_gaspar/gaspar_json.py", line 183, in <module>
    main()
  File "/etc/openhab2/scripts/gazpar/domoticz_gaspar/gaspar_json.py", line 128, in main
    dtostr(today))
  File "/etc/openhab2/scripts/gazpar/domoticz_gaspar/gaspar.py", line 150, in get_data_per_month
    return _get_data(session, 'Mois', start_date, end_date)
  File "/etc/openhab2/scripts/gazpar/domoticz_gaspar/gaspar.py", line 300, in _get_data
    d = md.group(1)
AttributeError: 'NoneType' object has no attribute 'group'

```

**Comment by TheSleepySlee** [comment]
Je vois dans d'autres commentaires que c'est sans doute dû aux instabilités du site GRDF. Combien de fois vous lancez le script par jour pour être sûr d'avoir des valeurs? Pour le moment, je ne le faisais que 2 fois par jour. Merci.

**Comment by biwizit** [comment]
Hello, je le fais 3 fois par jour : 8h, 13h et 18h.

Je confirme qu'un premier `"AttributeError: 'NoneType' object has no attribute 'group'"` est arrivé le 12 Août à 18h, et de nouveau le 13 Août à 18h (nickel entre les deux par contre).

Autour de cette période, il arrivait également que je récupère des `"urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0xb351b030>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution"` après le loggin successful; comme le 17 Août à 13h (mais tout a refonctionné à 18h par contre).

Donc oui, GRDF a semblé être un peu plus instable autour de cette mi-Août. 

Mais le vrai problème, c'est que ça ne fonctionne plus du tout depuis le 17 Août 18h. Voir l'issue #18 .

**Comment by TheSleepySlee** [comment]
Oui j'ai vu ça. Je travaille aussi sur la partie MQTT. J'ajouterai mon code lorsqu'il sera partageable dans #11

**Comment by ProfBoc75** [comment]
Hello All,

J'ai trouvé un contournement :  
1)- Pbm SSL : modifier le script gaspar.py  ligne 97 : 
 #session.get(LOGIN_BASE_URI + API_ENDPOINT_LOGIN, data=payload, allow_redirects=False)
session.get(LOGIN_BASE_URI + API_ENDPOINT_LOGIN, **verify=False**, data=payload, allow_redirects=False)

verify=False , ne vérifie plus le certif qui pose problème.

2)- Le pbm de Group persiste, mais c'est lié à un bug / erreur dans le même script , c'est pas **synthese** mais **consoDetaille** qu'il faut mettre , lignes 279 & 280 :  (reprendre à la place les mêmes lignes que 235 & 236)

'_eConso**synthese**_WAR_eConsoportlet__jsfBridgeAjax':'true',
'_eConso**synthese**_WAR_eConsoportlet__facesViewIdResource':'/views/conso/detaille/consoDetailleViewMode.xhtml'

'_eConsoconsoDetaille_WAR_eConsoportlet__jsfBridgeAjax':'true',
'_eConsoconsoDetaille_WAR_eConsoportlet__facesViewIdResource':'/views/conso/detaille/consoDetailleViewMode.xhtml'

J'ai bien récup mes consos avec ces 2 corrections.

![image](https://user-images.githubusercontent.com/62882637/91057085-0f1ea100-e627-11ea-9a6f-f5e0e6db396d.png)

**Comment by empierre** [comment]
je viens de commiter tes fixes, à tester

**Comment by biwizit** [comment]
C'est tout bon, merci ! 

`2020-08-24 17:44:41,249 logging in as xxx@yyy.fr...
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:849: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:849: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:849: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
2020-08-24 17:44:52,948 logged in successfully!
2020-08-24 17:44:52,949 retrieving data...
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:849: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:849: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:849: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:849: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:849: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:849: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
2020-08-24 17:45:01,539 got data!
269,1498,2702,2996,3571,1592,2834,1073,863,201,119,85
09/2019,10/2019,11/2019,12/2019,01/2020,02/2020,03/2020,04/2020,05/2020,06/2020,07/2020,08/2020
5,4,2,2,2,7,4,6,2,4,10,4
Le 12/08/2020,Le 13/08/2020,Le 14/08/2020,Le 15/08/2020,Le 16/08/2020,Le 17/08/2020,Le 18/08/2020,Le 19/08/2020,Le 20/08/2020,Le 21/08/2020,Le 22/08/2020,Le 23/08/2020

`
