### ISSUE TITLE
get more than 12 days

### ISSUE THREAD

**Issue by empierre** [empierre/domoticz_gaspar#2]

**Comment by empierre** [comment]
still in progress, heavy rewriting to do

**Comment by max5962** [comment]
Hello,
do you succed to retrieve more than 12 days ? :)

**Comment by empierre** [comment]
you had 12 days because you requested on day 12 ;-)

**Comment by empierre** [comment]
by design you can get only daily values of the last month... and aggregated from previous

**Comment by max5962** [comment]
Thanks. ( i'm feeling stupid now :) ) 
nice works by the way. I'm using it everyday to retrieve gaz data.
You can closed the issue

**Comment by empierre** [comment]
il faut maintenant passer sur l'autre plugin, cf page d'accueil
