### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by dltrainou** [empierre/domoticz_gaspar#20]
bonjour
je viens de remplacer le fichier gaspar.py , mais j'ai encore une erreur??
mes données sont nulles depuis le 13/08 en kwh, mais seulement depuis le 18/08 en m3, peut être est ce la cause?
une idée? merci d'avance

/usr/lib/python3/dist-packages/urllib3/connectionpool.py:845: InsecureRequestWarning: Unverified HTTPS request is being made. Addi$
InsecureRequestWarning)
2020-08-25 07:35:02,350 logged in successfully!
2020-08-25 07:35:02,351 retrieving data...
Traceback (most recent call last):
File "/home/pi/domoticz/scripts/gaspar/gaspar_json.py", line 187, in
main()
File "/home/pi/domoticz/scripts/gaspar/gaspar_json.py", line 126, in main
dtostr(today))
File "/home/pi/domoticz/scripts/gaspar/gaspar.py", line 150, in get_data_per_month
return _get_data(session, 'Mois', start_date, end_date)
File "/home/pi/domoticz/scripts/gaspar/gaspar.py", line 300, in _get_data
d = md.group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by empierre** [comment]
Envoies moi le contenu de la page + une capture d'écran de :
https://monespace.grdf.fr/monespace/particulier/consommation/consommations
sur domoticz@e-nef.com


et si tu peux évites de dupliquer pour un même sujet ;-)

**Comment by Ossetard** [comment]
Pour ma part j'ai le même soucis. 
Par contre mes données sont présentes en Kwh et m3 sur le site GRDF

**Comment by dltrainou** [comment]
mes excuses, le sujet précédent étant clos, je pensais qu'il fallait en rouvrir un.
j'ai envoyé la capture d'écran grdf par mois.
"Envoies moi le contenu de la page" de quelle page parles tu?
merci d'avance

**Comment by Ossetard** [comment]
bon pour ma part en relançant plein de fois le script j'ai fini par récupérer mes données....

**Comment by dltrainou** [comment]
bizarre, moi itou, a la xieme tentative, la base a été mise a jour. on le voit au temps d'accès, si l'on ressort trop vite du prg, c'est pas bon!! si il reste au moins 10-15s avant de rendre kla main , c'est ok.
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:845: InsecureRequestWa$
  InsecureRequestWarning)
2020-08-25 09:43:35,768 logged in successfully!
2020-08-25 09:43:35,769 retrieving data...
2020-08-25 09:43:49,355 got data!

**Comment by empierre** [comment]
ok, donc en fait c'est leur système qui met trop de temps à répondre et qui
doit renvoyer une page de timeout, et donc le programme ne trouve pas ses
balises...

**Comment by dltrainou** [comment]
Ok wait and see !! merci du taf en tous cas.

Je me demande s’il faut modifier la crontab pour augmenter la fréquence des accès ??

Bonne journée

 

De : Emmanuel <notifications@github.com> 
Envoyé : mardi 25 août 2020 10:11
À : empierre/domoticz_gaspar <domoticz_gaspar@noreply.github.com>
Cc : dltrainou <dltrainou@free.fr>; Author <author@noreply.github.com>
Objet : Re: [empierre/domoticz_gaspar] AttributeError: 'NoneType' object has no attribute 'group' (#20)

 

ok, donc en fait c'est leur système qui met trop de temps à répondre et qui
doit renvoyer une page de timeout, et donc le programme ne trouve pas ses
balises...

**Comment by empierre** [comment]
Hello,

  Il faut *absolument* limiter les accès concurrents car sinon ils vont
faire comme linky un captcha et ce sera la fin...

  Le mieux c'est de le faire à des horaires décalés (comme avant 6h du
matin) car de toutes les façons ce sont les données de la veille.

**Comment by dltrainou** [comment]
Ok c'est déjà le cas, je ne le lance que la nuit, je le laisse donc à 3 accès. Merci et bonne journée Envoyé depuis mon smartphone Samsung Galaxy.
-------- Message d'origine --------De : Emmanuel <notifications@github.com> Date : 25/08/2020  10:26  (GMT+01:00) À : empierre/domoticz_gaspar <domoticz_gaspar@noreply.github.com> Cc : dltrainou <dltrainou@free.fr>, Author <author@noreply.github.com> Objet : Re: [empierre/domoticz_gaspar] AttributeError: 'NoneType' object has
  no attribute 'group' (#20) 

Hello,



  Il faut *absolument* limiter les accès concurrents car sinon ils vont

faire comme linky un captcha et ce sera la fin...



  Le mieux c'est de le faire à des horaires décalés (comme avant 6h du

matin) car de toutes les façons ce sont les données de la veille.

**Comment by empierre** [comment]
il faut maintenant passer sur l'autre plugin, cf page d'accueil
