### ISSUE TITLE
Error while executing domoticz_gazpar

### ISSUE THREAD

**Issue by djs45** [empierre/domoticz_gaspar#23]
Hello
I can't receive any data. Here is the error :
pi@raspberrypi:~/domoticz_gaspar $ ./domoticz_gaspar.sh
Error: near line 1: near "Exception": syntax error

What can I do ?

Many thanks, BR, Sébastien

**Comment by empierre** [comment]
Hello,

  Line 1 is:
#!/bin/sh

do you have the alias on your box ? maybe replace it with bash if you miss the link (if so you must have others things not working well, common alias for shell under linux)

**Comment by djs45** [comment]
Thank you for your answer.
I don't have alias. 
The program run (i have some json).
My gazpar counter is operationnal since today so it can be the problem ?

**Comment by empierre** [comment]
il faut maintenant passer sur l'autre plugin, cf page d'accueil
