### ISSUE TITLE
Pas d'ouverture de Database

### ISSUE THREAD

**Issue by jiji45** [empierre/domoticz_gaspar#27]
Bonjour.
Si je lance ./domoticz_gaspar.sh.     j'obtiens le résultat suivant
:
pi@pi:~/domoticz_gaspar $ ./domoticz_gaspar.sh
Error: unable to open database "/home/pi/domoticz/domoticz.db": unable to open database file

Puis-je avoir votre aide SVP

Merci d'avance pour votre retour.
Clt

**Comment by empierre** [comment]
bonjour,

  c'est le chemin d'access vers domoticz et sa bdd, le changer ou faire un
lien symbolique...

  visiblement tu n'utilises pas de raspberry pi

**Comment by jiji45** [comment]
bonjour Emmanuel.

Merci pour cette réponse.

Si j'utilise un raspberry, mais je suis en SSH a partir de mon mac.

Je ne saisi pas où et comment changer ce chemin d'accés.... (désolé je suis un peu nul)

Clt

**Comment by empierre** [comment]
quel est le chemin d'acces de domoticz ?

**Comment by empierre** [comment]
il faut definir la variable HOME dans le. sh quand tu l'auras

**Comment by jiji45** [comment]
bonjour, le chemin d'accès de Domoticz est 

root@pi:/home/pi/domoticz

**Comment by empierre** [comment]
donc un probleme de droits, il faut que ca toutne sous le meme user ou
sinon tu mets domoticz.db en 777

**Comment by jiji45** [comment]
cela ne change rien.

Toujours ce message:
Error: unable to open database "/home/pi/domoticz/domoticz.db": unable to open database file

**Comment by jiji45** [comment]
je me retrouve avec deux fichier Device

1 fichier domoticz.db avec "d" minuscule, fichier de type inconnu et:
1 fichier Domoticz.db avec "D" majuscule, fichier de type SQLite3

Dans lequel des deux sont écrits les données issues de domoticz_gaspar.sh?

**Comment by jiji45** [comment]
Après changement des droits d'accès, et en lançant.  ./domoticz_gaspar.sh, j'obtiens le message ci dessous.Error: near line 1: near "Exception": syntax error

**Comment by empierre** [comment]
Hello,

  sur une installe pure unix, c'est bien du sqlite mais avec un d
minuscule.c'est le bon normalement. le fait que tu en ait deux signifie
qu'il y a un soucis quelquepart, ton domoticz fonctionne bien ? si tu
l'arrêtes, quel est le dernier des deux qui est enregistré ?
