### ISSUE TITLE
Pas de remontées des consommations sur le panneau 'Usage Last Year"

### ISSUE THREAD

**Issue by lolo-b** [empierre/domoticz_gaspar#28]
Bonjour,

Tout d'abord, bravo pour ce programme. De mon coté, cela fonctionne "presque" bien.

Je n'ai pas le détail de ma consommation dans la journée, il semblerait qu'il faut souscrire une option payante.

J'ai bien la remontée de ma consommations par jour et par mois (voir fichiers json). Par contre sous domoticz, je visualise bien ma consommation de la semaine (panneau "Usage Last week) et dans le mois écoulé (Usage Last Month). 

Dans le panneau de consommation de l'année écoulée, j'ai la visualisation que sur le dernier mois, bien que le fichier export_months_values.json contient toutes mes consommations depuis janvier 2021!

Que faire ?

capture d'écran:
![Capture ecran](https://user-images.githubusercontent.com/63586580/142729579-7d7b774c-f103-4761-9166-5b7af29b21c2.png)
fichiers json et sql:
[export_days_values.json.txt](https://github.com/empierre/domoticz_gaspar/files/7574652/export_days_values.json.txt)
[export_months_values.json.txt](https://github.com/empierre/domoticz_gaspar/files/7574653/export_months_values.json.txt)
[req.sql.txt](https://github.com/empierre/domoticz_gaspar/files/7574654/req.sql.txt)

**Comment by empierre** [comment]
Hello,

  Sur l'horaire, il n'y a pas de courbe de charge dans le gaz comme en
électricité, même en payant je ne suis pas sur que ce soit récupérable...

  Pour l'historique, domoticz transforme le journalier en mensuel puis
annuel, de mémoire (car cela date déjà) je ne crois pas que ce soit
possible juste d'injecter un mensuel passé car il fonctionne en incrément
d'index de relève pour le calcul
