### ISSUE TITLE
XMLSyntaxError: Opening and ending tag mismatch

### ISSUE THREAD

**Issue by peyrouse** [empierre/domoticz_gaspar#29]
Bonjour,
Merci pour cet outil qui a très bien fonctionné pendant 1 an. Depuis quelques jours je n'ai plus la conso dans Domoticz et j'ai l'erreur suivante dans le log :
2021-11-24 10:30:41,846 logging in as xxxxxxxx@gmail.com...
Traceback (most recent call last):
  File "/home/pi/domoticz_gaspar/gaspar_json.py", line 179, in <module>
    main()
  File "/home/pi/domoticz_gaspar/gaspar_json.py", line 113, in main
    token = gaspar.login(USERNAME, PASSWORD)
  File "/home/pi/domoticz_gaspar/gaspar.py", line 101, in login
    javaxvs2=parse_lxml(req.text)
  File "/home/pi/domoticz_gaspar/gaspar.py", line 61, in parse_lxml
    root = etree.fromstring(c)
  File "src/lxml/etree.pyx", line 3222, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1877, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1758, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1068, in lxml.etree._BaseParser._parseUnicodeDoc
  File "src/lxml/parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 711, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 640, in lxml.etree._raiseParseError
  File "<string>", line 6
lxml.etree.XMLSyntaxError: Opening and ending tag mismatch: hr line 5 and body, line 6, column 8

Savez-vous d'où provient le problème ?
Merci d'avance pour votre aide.

**Comment by gb78500** [comment]
Bonjour,
Je rencontre le même problème. J'imagine que c'est lié à la mise en place du nouveau site GRDF.

**Comment by empierre** [comment]
oui ils ont refait leur site web, il va falloir tout refaire...

**Comment by empierre** [comment]
bon ça semble un poil plus simple si je passe l'authent, on peut
télécharger le fichier et le transformer en csv


https://monespace.grdf.fr/api/e-conso/pce/consommation/informatives/telecharger?dateDebut=2018-11-24&dateFin=2021-11-24&frequence=Journalier&pceList%5B%5D=aaaa

**Comment by dranreb38** [comment]
Bonjour,
Idem en place depuis 3 ans sans pb.... En attendant les correctifs d' @empierre j'importe le fichier en manuel.

**Comment by empierre** [comment]
c'est pas du correctif, y'a de l'oauth2 avec nginx f5 et okta...  si je
peix recuperer le token on sera bon sinon...

**Comment by dranreb38** [comment]
Effectivement ce n'est pas un simple correctif, mais une refonte complète , dans mon esprit c’était bien cela !.
Merci pour ton travail Emmanuel !

**Comment by empierre** [comment]
forgerock, okta, nginx... si je passe tout ça on sera bon... pas gagné...

**Comment by jiji45** [comment]
Bonjour.
Je rencontre des problèmes de relevé depuis le 21 novembre, est-ce dû a ce que je viens de lire ici????
Pardonnez mon ignorance, mais je suis un peu nul en informatique.
Bien cordialement

**Comment by empierre** [comment]
oui

**Comment by Scrat95220** [comment]
Pour info, j'ai refais un script python de 0 qui utilise le nouveau site et ça marche nickel. Je vais le modifier pour qu'il soit plus propre et complètement configurable

**Comment by biwizit** [comment]
> Pour info, j'ai refais un script python de 0 qui utilise le nouveau site et ça marche nickel. Je vais le modifier pour qu'il soit plus propre et complètement configurable

Génial ça ! J'espère que tu le mettras quelque part sur Github (une branche ici ou un projet ailleurs). Merci !

**Comment by dranreb38** [comment]
> Génial ça ! J'espère que tu le mettras quelque part sur Github (une branche ici ou un projet ailleurs). Merci !

+1

**Comment by ProfBoc75** [comment]
Bonsoir, 

Je sais que le plugin en l'état ne remonte plus d'info, je vais donc voir sur le site GRDF pour importer manuellement , et là , mes dernières données s'arrêtent le 23 Novembre, est-ce pareil pour vous ?

**Comment by pbda** [comment]
Pareil !

**Comment by Sebastiii** [comment]
Idem !

**Comment by dranreb38** [comment]
+1 idem, arrêt au 23/11

**Comment by Scrat95220** [comment]
Bonjour, voici le script qui fonctionne avec le nouveau site : https://github.com/Scrat95220/DomoticzGazpar
J'ai crée un nouveau repo car au final malgré que je sois à la base parti du script fonctionnant avec l'ancien site j'ai tout cassé pour que cela fonctionne uniquement avec du Python.

**Comment by dranreb38** [comment]
Merci @Scrat95220 , je teste dès que les valeurs sont de nouveaux en ligne !
J'ai une erreur dans le traitement du login
`Traceback (most recent call last):
  File "/home/pi/domoticz/DomoticzGazpar/gazpar.py", line 32, in <module>
    USERNAME = os.environ['GAZPAR_USERNAME']
  File "/usr/lib/python3.7/os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'GAZPAR_USERNAME'
Traceback (most recent call last):
  File "/home/pi/domoticz/DomoticzGazpar/gazpar.py", line 32, in <module>
    USERNAME = os.environ['GAZPAR_USERNAME']
  File "/usr/lib/python3.7/os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'GAZPAR_USERNAME'
root@domoticz:/home/pi/domoticz/DomoticzGazpar#`

**Comment by empierre** [comment]
Hello,

  Joli ! tu as réussi à le faire sans l'identifiant de domicile ?

**Comment by ProfBoc75** [comment]
Hello, 

De mon coté j'ai 3 nouvelles données du 24, 25 et 26 mises à jour sur le site GRDF. Ils sont à la bourre dans les batchs visiblement ...

**Comment by Sebastiii** [comment]
J'ai testé le script :)
Il fonctionne bien, et effectivement, il y a des nouvelles dates.
Jusqu'au 27/11.

J'ai une erreur si je demande trop de jour (150, c'est bon et 200 j'ai l'erreur)
`Traceback (most recent call last):
  File "/app/domoticz_gaspar/gazpar.py", line 141, in <module>
    main()
  File "/app/domoticz_gaspar/gazpar.py", line 132, in main
    generate_db_script(token, dtostr(today - relativedelta(days=int(nbDaysImported))), \
  File "/app/domoticz_gaspar/gazpar.py", line 105, in generate_db_script
    index = index + conso
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'`

En tout cas, ca fonctionne de nouveau, et j'ai pu constater que je consomme plus que l'an dernier, donc je dois avoir un réglage pas correct sur mon plancher chauffant vu que j'ai réduit la température des pieces LOL (mais c'est hors sujet)

**Comment by Scrat95220** [comment]
> Hello, Joli ! tu as réussi à le faire sans l'identifiant de domicile ?

Si tu parles du numéro de PCE, il y a un service qui permet d'avoir l'info

**Comment by ProfBoc75** [comment]
> Merci @Scrat95220 , je teste dès que les valeurs sont de nouveaux en ligne ! J'ai une erreur dans le traitement du login `Traceback (most recent call last): File "/home/pi/domoticz/DomoticzGazpar/gazpar.py", line 32, in <module> USERNAME = os.environ['GAZPAR_USERNAME'] File "/usr/lib/python3.7/os.py", line 678, in __getitem__ raise KeyError(key) from None KeyError: 'GAZPAR_USERNAME' Traceback (most recent call last): File "/home/pi/domoticz/DomoticzGazpar/gazpar.py", line 32, in <module> USERNAME = os.environ['GAZPAR_USERNAME'] File "/usr/lib/python3.7/os.py", line 678, in __getitem__ raise KeyError(key) from None KeyError: 'GAZPAR_USERNAME' root@domoticz:/home/pi/domoticz/DomoticzGazpar#`

C'est parce qu'il faut modifier le fichier cfg avec GA**Z**PAR_USERNAME avec un Z  , anciennement (version empierre) avec GA**S**PAR_USERNAME avec un S.

**Comment by Scrat95220** [comment]
> J'ai testé le script :) Il fonctionne bien, et effectivement, il y a des nouvelles dates. Jusqu'au 27/11.
> 
> J'ai une erreur si je demande trop de jour (150, c'est bon et 200 j'ai l'erreur) `Traceback (most recent call last): File "/app/domoticz_gaspar/gazpar.py", line 141, in <module> main() File "/app/domoticz_gaspar/gazpar.py", line 132, in main generate_db_script(token, dtostr(today - relativedelta(days=int(nbDaysImported))), \ File "/app/domoticz_gaspar/gazpar.py", line 105, in generate_db_script index = index + conso TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'`
> 
> En tout cas, ca fonctionne de nouveau, et j'ai pu constater que je consomme plus que l'an dernier, donc je dois avoir un réglage pas correct sur mon plancher chauffant vu que j'ai réduit la température des pieces LOL (mais c'est hors sujet)

J'ai testé 120j max chez moi car je n'ai pas de donné avant... Je regarderais pourquoi ça crash, peut être une limitation

**Comment by Scrat95220** [comment]
Juste une chose, si vous vous trompez une fois de password, le site va redemander de valider la catpcha et le script ne fonctionnera plus.
Dans ce cas il faut aller sur le site web et se logguer juste une fois en validant le catpcha et c'est reparti

**Comment by onlinux** [comment]
Pour corriger l'erreur TypeError: unsupported operand type(s) for +: 'int' and 'NoneType' voir l'issue que j'ai posté sur le Git de Scrat95220 (https://github.com/Scrat95220/DomoticzGazpar)

Lorsque un relevé est manquant 'Absence de Données' le script plante.
ex: {'dateDebutReleve': '2021-11-16T06:00:00+01:00', 'dateFinReleve': '2021-11-17T06:00:00+01:00', 'journeeGaziere': '2021-11-16', 'indexDebut': None, 'indexFin': None, 'volumeBrutConsomme': None, 'energieConsomme': None, 'pcs': None, 'volumeConverti': None, 'pta': None, 'natureReleve': None, 'qualificationReleve': 'Absence de Données', 'status': None, 'coeffConversion': None, 'frequenceReleve': None, 'temperature': None}

Correction proposée:
<pre>
for releve in j[str(numPce)]['releves']:
        print(releve)
        req_date = releve['journeeGaziere']
        conso = releve['energieConsomme']
        try :
            index = index + conso
        except TypeError:
            print(req_date, conso, index, "Invalid Entry")
            continue
</pre>
Et ca marche.

**Comment by ProfBoc75** [comment]
> > J'ai testé le script :) Il fonctionne bien, et effectivement, il y a des nouvelles dates. Jusqu'au 27/11.
> > J'ai une erreur si je demande trop de jour (150, c'est bon et 200 j'ai l'erreur) `Traceback (most recent call last): File "/app/domoticz_gaspar/gazpar.py", line 141, in <module> main() File "/app/domoticz_gaspar/gazpar.py", line 132, in main generate_db_script(token, dtostr(today - relativedelta(days=int(nbDaysImported))), \ File "/app/domoticz_gaspar/gazpar.py", line 105, in generate_db_script index = index + conso TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'`
> > En tout cas, ca fonctionne de nouveau, et j'ai pu constater que je consomme plus que l'an dernier, donc je dois avoir un réglage pas correct sur mon plancher chauffant vu que j'ai réduit la température des pieces LOL (mais c'est hors sujet)
> 
> J'ai testé 120j max chez moi car je n'ai pas de donné avant... Je regarderais pourquoi ça crash, peut être une limitation

La limite semble être de 3 ans, à 1096 Jours ça passe, à 1097 ça plante. ( 3x365 = 1095 + 1 jour bissextile 2020 ?? = 1096)
Tout dépend de quand votre compteur a été installé aussi, moi c'était en 2018.

**Comment by Sebastiii** [comment]
> Pour corriger l'erreur TypeError: unsupported operand type(s) for +: 'int' and 'NoneType' voir l'issue que j'ai posté sur le Git de Scrat95220 (https://github.com/Scrat95220/DomoticzGazpar)

> Et ca marche.

Super :) ça marche nickel merci.

**Comment by Sebastiii** [comment]
> La limite semble être de 3 ans, à 1096 Jours ça passe, à 1097 ça plante. ( 3x365 = 1095 + 1 jour bissextile 2020 ?? = 1096) Tout dépend de quand votre compteur a été installé aussi, moi c'était en 2018.

Du coup, j'ai mis aussi 1096 ;) pour tester et ça a fonctionné aussi.

**Comment by pierrecelle38** [comment]
ils sont en train de nous mettre un captcha ... marre de ces sites qui ne proposent pas d'api et qui bloque tout

**Comment by dranreb38** [comment]
Grrr !
![Screenshot_338](https://user-images.githubusercontent.com/16446911/144427693-b9d9c1da-183a-4d89-ad22-22fbcf7dd828.png)

**Comment by onlinux** [comment]
Bonsoir à tous,

 J'ai ajouté la possibilité d'alimenter un compteur Gaz en m3 au code de Scratc95220.
Voir Pull request https://github.com/Scrat95220/DomoticzGazpar/pull/3

**Comment by Scrat95220** [comment]
> Bonsoir à tous,
> 
> J'ai ajouté la possibilité d'alimenter un compteur Gaz en m3 au code de Scratc95220. Voir Pull request [Scrat95220/DomoticzGazpar#3](https://github.com/Scrat95220/DomoticzGazpar/pull/3)

Jolie !! Je comptais le faire aussi mais pas eu le temps.

**Comment by empierre** [comment]
Hello,

  Visiblement les dernières version de sqlite3 (ubuntu pour ma part)
crashend la bdd domoticz... donc il faut stopper domoticz puis le
redémarrer avant d'injecter les valeurs....

**Comment by Sebastiii** [comment]
Pour ceux qui savent coder, vu que c'est du python, il y a peut-être un moyen de modifier le script directement pour un plugin domoticz (comme ça, plus de pb avec la DB) ?
Ou alors passer par l'alimentation des valeurs par l'intégration de l'URL web ?
Après vu que l'on intègre pas mal d'information, ça peut aussi faire planter Domoticz :(

**Comment by empierre** [comment]
Hello,

  en fait c'est mon domoticz qui a un soucis, plantage de base régulière
sur la dernière beta et (ou pas )lié à des updates de libs ... il a planté
à 6h ce matin encore sans raison

  bref grosse galère... et ticket ouvert chez domoticz.

**Comment by Sebastiii** [comment]
Esperons pour un fix rapide alors !

**Comment by usky73** [comment]
Bonjour, j'ai raté un épisode ou on est encore coincé ?

**Comment by empierre** [comment]
oui, c'est sur la page d'accueil:
This module has been deprecated, please use : https://github.com/Scrat95220/DomoticzGazpar

**Comment by usky73** [comment]
Arg, je suis passé à coté !
Merci.

**Comment by empierre** [comment]
j'ai un script de migration du device sur l'accueil github car le type est différent, il fait le mapping de l'ancien au nouveau device sur l'historique.
