### ISSUE TITLE
Does it still working  ??

### ISSUE THREAD

**Issue by Minims** [empierre/domoticz_gaspar#5]
I have this error : 

```
/home/pi/github/domoticz_gaspar/gaspar.py:199: SyntaxWarning: name 'JAVAVXS' is used prior to global declaration
  global JAVAVXS
2018-06-04 10:03:37,529 logging in as *********...
2018-06-04 10:03:40,706 logged in successfully!
2018-06-04 10:03:40,706 retrieving data...
Traceback (most recent call last):
  File "gaspar_json.py", line 179, in <module>
    main()
  File "gaspar_json.py", line 124, in main
    dtostr(today))
  File "/home/pi/github/domoticz_gaspar/gaspar.py", line 143, in get_data_per_month
    return _get_data(session, 'Mois', start_date, end_date)
  File "/home/pi/github/domoticz_gaspar/gaspar.py", line 283, in _get_data
    d = md.group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

1. JAVAXS, i don't know why  i have this.
2. On line 283 line, i have this for req.text : 
`<partial-response><changes><update id="javax.faces.ViewState"><![CDATA[-**************:***************]]></update></changes></partial-response>`

I have made the call from curl, i have the same response.

**Comment by empierre** [comment]
these are states variables from jsf, maybe they have changed the table, will have to have a look

**Comment by JujuBickoille** [comment]
I got exactly same error, I'll try to fix it !

That's great to have access to gazpar informations !

**Comment by JujuBickoille** [comment]
I've compared with my webbrowser, I got same empty "partial response" when I call again the SAME consommations page. I think it look like to a " caching " system don't resend same datas ?

I'll try to understand it more !

**Comment by colinleroy** [comment]
Same problem here. Did you manage to reproduce that, @empierre ?
Thanks in advance !

**Comment by empierre** [comment]
hello, lot of fixes, still not finished but working again
