### ISSUE TITLE
erreur

### ISSUE THREAD

**Issue by ganq76** [empierre/domoticz_gaspar#6]
bonjour, 
j'ai cette erreur dans le log : 
 cat domoticz_gaspar.log
/home/pi/domoticz/scripts/domoticz_gaspar/gaspar.py:199: SyntaxWarning: name 'JAVAVXS' is used prior to global declaration
  global JAVAVXS
Traceback (most recent call last):
  File "/home/pi/domoticz/scripts/domoticz_gaspar/gaspar_json.py", line 26, in <module>
    import gaspar
  File "/home/pi/domoticz/scripts/domoticz_gaspar/gaspar.py", line 29, in <module>
    from lxml import etree
ImportError: No module named 'lxml'

**Comment by JujuBickoille** [comment]
Visiblement, vous n'avez pas le module lxml d'installé. Sous debian, j'ai installé python-lxml ( et python3-lxml pour Python3 )

**Comment by ganq76** [comment]
Bonjour, merci de votre réponse. J'ai installé les 2 modules, mais j'ai toujours la même erreur. Je suis sous raspberry pi.

**Comment by empierre** [comment]
sudo apt-get install python3-lxml

et ça fonctionne !
